// Generated by tools/diagnostics/generate_autocapture_format.py; do not edit.
#pragma once
#include "common.h"
struct MHeader {
    u32 magic;
    u32 version;
    u32 header_size;
    u32 record_size;
    u32 capacity;
    u32 write_index;
    u32 total_samples;
    u32 game_code;
    u32 rom_size;
    u32 sequence;
    u32 flags;
    u32 status;
    u32 file_result;
    u32 checksum;
    u32 first_vblank_sample;
    u32 transition_sample;
    u32 stages;
    u32 first_a_sample;
    u32 a_count;
    u32 last_success_sample;
    u32 first_low_sample;
    u32 low_event_count;
    u32 event_count;
    u32 phase_write_index;
    u32 phase_total;
    u32 phase_capacity;
    u32 event_capacity;
    u32 event_record_size;
    u32 complete_size;
    u32 rom_header_hash;
    u32 save_size;
    u32 dsi_mode;
    u32 mount_device;
    u32 clock_control;
    u32 app_config_loaded;
    u32 title_config_loaded;
    u32 config_path_hash;
    u32 config_data_hash;
    u32 env_valid;
    u32 stack_flags;
    u32 stack_used;
    u32 write_start_vcount;
    u32 write_end_vcount;
    u32 build_id_0;
    u32 build_id_1;
    u32 build_id_2;
    u32 build_id_3;
    u32 build_id_4;
    u32 build_id_5;
    u32 build_id_6;
    u32 build_id_7;
    u32 build_id_8;
    u32 build_id_9;
    u32 first_low_target;
    u32 first_low_source;
    u32 first_low_spsr;
    u32 first_low_kind;
    u32 fs_failures;
    u32 last_attempt_sample;
    u32 stack_size;
    u32 event_stack_size;
    u32 reserved0;
    u32 reserved1;
    u32 reserved2;
};
struct MEvent {
    u32 sample;
    u32 kind;
    u32 source;
    u32 target;
    u32 native_spsr;
    u32 virtual_cpsr;
    u32 irq_spsr;
    u32 irq_lr;
    u32 irq_sp;
    u32 marker;
    u32 hicode_block;
    u32 mpu_region4;
    u32 icache_lockdown;
    u32 instruction;
    u32 instruction_valid;
    u32 sequence;
};
enum MExtra {
    X_NATIVE_SPSR = 0,
    X_DS_IME = 1,
    X_MPU_REGION4 = 2,
    X_ICACHE_LOCKDOWN = 3,
    X_CP15_CONTROL = 4,
    X_VM_SPSR_IRQ = 5,
    X_VM_LR_IRQ = 6,
    X_VM_SP_IRQ = 7,
    X_NESTED_IRQ_LEVEL = 8,
    X_DS_MASTER_BRIGHTNESS = 9,
    X_DS_CAPTURE_CONTROL = 10,
    X_DS_VRAM_ABCD = 11,
    X_DS_VRAM_EFG = 12,
    X_STAGES = 13,
    X_FS_RESULT = 14,
    X_LAST_SUCCESS_SAMPLE = 15,
    X_TRANSITION_SAMPLE = 16,
    X_SD_OLD_BLOCK = 17,
    X_SD_NEW_BLOCK = 18,
    X_SD_CACHE_BLOCK = 19,
    X_SD_LOAD_COUNT = 20,
    X_WRITE_START_VCOUNT = 21,
    X_WRITE_END_VCOUNT = 22,
    X_STACK_FLAGS = 23,
    X_STACK_USED = 24,
    X_NATIVE_IRQ_LR = 25,
    X_FIRST_LOW_TARGET = 26,
    X_EVENT_COUNT = 27,
    X_KEY_EDGES = 28,
    X_ANCHOR_REASON = 29,
    X_SOURCE_INSTRUCTION = 30,
    X_SOURCE_INSTRUCTION_VALID = 31,
};
constexpr u32 M_RUNTIME_CAPACITY = 64;
constexpr u32 M_PHASE_CAPACITY = 16;
constexpr u32 M_EVENT_CAPACITY = 8;
constexpr u32 M_STACK_SIZE = 8192;
constexpr u32 M_EVENT_STACK_SIZE = 2048;
constexpr u32 M_PERSIST_INTERVAL = 60;
constexpr u32 M_HEADER_SIZE = 256;
constexpr u32 M_RECORD_SIZE = 372;
constexpr u32 M_EXTRA_COUNT = 32;
constexpr u32 M_COMPLETE_SIZE = M_HEADER_SIZE + M_RECORD_SIZE * (M_RUNTIME_CAPACITY + M_PHASE_CAPACITY) + sizeof(MEvent) * M_EVENT_CAPACITY;
static_assert(sizeof(MHeader) == M_HEADER_SIZE);
