#!/usr/bin/env python3
"""One schema supplies C++ sizes, decoder geometry, and artifact instructions."""
import argparse
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
SCHEMA = json.loads((HERE / 'autocapture_schema.json').read_text())
TARGET = HERE.parents[1] / 'code/core/arm9/source/Diagnostics/AutoCaptureFormat.h'

def generated():
    s = SCHEMA
    lines = ['// Generated by tools/diagnostics/generate_autocapture_format.py; do not edit.',
             '#pragma once', '#include "common.h"',
             'struct MHeader {']
    lines += ['    u32 ' + n + ';' for n in s['header']]
    lines += ['};', 'struct MEvent {']
    lines += ['    u32 ' + n + ';' for n in s['event']]
    lines += ['};', 'enum MExtra {']
    lines += [f'    X_{n.upper()} = {i},' for i, n in enumerate(s['extra'])]
    lines += ['};']
    for key in ('runtime_capacity', 'phase_capacity', 'event_capacity', 'stack_size', 'event_stack_size', 'persist_interval'):
        lines += [f'constexpr u32 M_{key.upper()} = {s[key]};']
    lines += [f'constexpr u32 M_HEADER_SIZE = {4*len(s["header"])};',
              f'constexpr u32 M_RECORD_SIZE = {244+4*len(s["extra"])};',
              f'constexpr u32 M_EXTRA_COUNT = {len(s["extra"])};',
              'constexpr u32 M_COMPLETE_SIZE = M_HEADER_SIZE + M_RECORD_SIZE * (M_RUNTIME_CAPACITY + M_PHASE_CAPACITY) + sizeof(MEvent) * M_EVENT_CAPACITY;',
              'static_assert(sizeof(MHeader) == M_HEADER_SIZE);', '']
    return '\n'.join(lines)

if __name__ == '__main__':
    p = argparse.ArgumentParser(); p.add_argument('--check', action='store_true'); a = p.parse_args()
    if a.check:
        assert TARGET.read_text() == generated(), 'generated format is stale'
    else:
        TARGET.write_text(generated(), newline='\n')
    print('autocapture format: header', 4*len(SCHEMA['header']), 'record', 244+4*len(SCHEMA['extra']))
